### ISSUE TITLE
Error 'The program 'docker' is currently not installed. You can install it by typing: sudo apt-get install docker'

### ISSUE THREAD

**Issue by janki1996** [qwertangel/darkflow-docker#1]
While installing I receive the above mentioned error.

**Comment by carefulcomputer** [comment]
you need to install docker to use this. you can install docker on your machine (assuming you are using ubuntu) by following instructions here

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

if you have issues with docker, please check linux/docker forums

**Comment by janki1996** [comment]
Thanks it worked!
