### ISSUE TITLE
Link cfg and image frames using docker

### ISSUE THREAD

**Issue by janki1996** [qwertangel/darkflow-docker#2]
The readme file has this 'docker run -v /tmp:/images -ti darkflow bash'. So how should I link the cfg and the data to run your module? What should tmp and image folder contain?

**Comment by carefulcomputer** [comment]
this command will get inside docker shell. if by data you mean weights, they are already downloaded into root folder of docker.
copy detect.py file inside docker root and change the rtsp url/username/password and run it with 

python detect.py

that should fetch images from your remote cam and do person detection. If any person is detected, it will save detected images in your /tmp folder. 
if you want to do just run detection (all objects) on static images then create a folder /tmp/testimages and put  your images in it. Then inside docker run this command

flow --imgdir /images/testImages/ --model /darkflow/cfg/yolo.cfg --load /yolo.weights

That will create a folder called /tmp/testimages/out and have your detection results in that folder.

**Comment by janki1996** [comment]
i want to run on static images. I get this error 
"No such file or directory: './cfg/coco.names' "
Also, where should I make /tmp/testimages folder? In the folder containing Dockerfile?

**Comment by LarsAC** [comment]
Same here about the ./cfg/coco.names. Any help?
